---
grails:
    profile: web
    codegen:
        defaultPackage: cn.edu.bnuz.bell
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
    default_schema: tm
    hbm2ddl:
        schema_filter_provider: cn.edu.bnuz.bell.orm.BellSchemaFilterProvider

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: cn.edu.bnuz.bell.orm.BellPostgreSQLDialect

environments:
    development:
        dataSource:
            dbCreate: none
            logSql: true
    test:
        dataSource:
            dbCreate: none
    production:
        dataSource:
            dbCreate: none
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
security:
    oauth2:
        client:
            accessTokenUri: http://localhost/uaa/oauth/token
            userAuthorizationUri: http://localhost/uaa/oauth/authorize
            clientId: acme
            clientSecret: acmesecret
            scope: openid
        resource:
            userInfoUri: http://localhost/uaa/user

spring:
    application:
        name: ${info.app.name}

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    session:
        timeout: 1200

bell:
    application:
        menu:
            expiration: 6

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 31000
ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 30000
